### ISSUE TITLE
Error when manually adding lead with custom framework

### ISSUE THREAD

**Issue by eoglethorpe** [eoglethorpe/deep#475]
Works fine with URL submission but not manual entry or attachment:

http://www.thedeep.io/214/entries/add/20296/

```
Internal Server Error: /214/entries/add/20296/
Traceback (most recent call last):
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "./entries/views.py", line 262, in get
    return render(request, "entries/add-template-entry.html", context)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/defaulttags.py", line 319, in render
    match = condition.eval(context)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/defaulttags.py", line 951, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "/home/ubuntu/code/venv/lib/py3.4/lib/python3.4/site-packages/django/template/base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  File "./leads/templatetags/startswith.py", line 8, in startswith
    return text.startswith(starts)
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by bibekdahal** [comment]
I have updated a fix. Since I don't have permission to this project, can you re-check and close if it is fixed?

**Comment by eoglethorpe** [comment]
Hm no still same problem (assuming there’s the latest code on the prod server?)

**Comment by bibekdahal** [comment]
It seems to work now (I added myself as it's member).

I guess, the prod server wasn't updated properly.
